// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package main

import "fmt"

func CoordInSlice(a Coord, list []Coord) bool {
	for _, b := range list {
		if b == a {
			return true
		}
	}
	return false
}

func MapCoordsToStrings(a []Coord) []string {
	result := make([]string, len(a))
	for i := 0; i < len(a); i++ {
		result[i] = fmt.Sprint(a[i])
	}

	return result
}

func RemoveFromCoordSlice(slice []Coord, idx int) []Coord {
	return append(slice[:idx:idx], slice[idx+1:]...)
}

func CloneCoordSlice(slice []Coord) []Coord {
	cloned := make([]Coord, len(slice))
	for i := 0; i < len(slice); i++ {
		cloned[i] = slice[i]
	}

	return cloned
}

func TileInSlice(a Tile, list []Tile) bool {
	for _, b := range list {
		if b == a {
			return true
		}
	}
	return false
}

func MapTilesToStrings(a []Tile) []string {
	result := make([]string, len(a))
	for i := 0; i < len(a); i++ {
		result[i] = fmt.Sprint(a[i])
	}

	return result
}

func RemoveFromTileSlice(slice []Tile, idx int) []Tile {
	return append(slice[:idx:idx], slice[idx+1:]...)
}

func CloneTileSlice(slice []Tile) []Tile {
	cloned := make([]Tile, len(slice))
	for i := 0; i < len(slice); i++ {
		cloned[i] = slice[i]
	}

	return cloned
}
