// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package main

import "fmt"

func IntArrayInSlice(a IntArray, list []IntArray) bool {
	for _, b := range list {
		if b.Equals(a) {
			return true
		}
	}
	return false
}

func MapIntArraysToStrings(a []IntArray) []string {
	result := make([]string, len(a))
	for i := 0; i < len(a); i++ {
		result[i] = fmt.Sprint(a[i])
	}

	return result
}

func RemoveFromIntArraySlice(slice []IntArray, idx int) []IntArray {
	return append(slice[:idx:idx], slice[idx+1:]...)
}

func CloneIntArraySlice(slice []IntArray) []IntArray {
	cloned := make([]IntArray, len(slice))
	for i := 0; i < len(slice); i++ {
		cloned[i] = slice[i]
	}

	return cloned
}
